### PR TITLE
Add endpoints for sending message and uploading image

### PR DESCRIPTION
**Pull request by chloepouprom**
New endpoints for sending messages and uploading images.

`POST /appUsers/:appUser/messages`
`POST /appUsers/:appUser/images`

@dannytranlx @mspensieri @jugarrit

### CODE REVIEW

**Comment by dannytranlx** [comment]
👍

**Comment by mspensieri** [comment]
Can we remove the deprecated endpoints?

**Comment by lemieux** [comment]
I would throw an error, not a warning... We really don't want them to use
those endpoints anymore.

**Comment by mspensieri** [comment]
Isn't throwing an error just as much of a breaking change as removing an API? Still would require a major version bump

**Comment by chloepouprom** [comment]
Gonna stay with current approach since our SDKs shouldn't allow users to use deprecated stuff

**Comment by chloepouprom** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4pQhEBzO&#x2F;4343-smooch-core-add-new-endpoints"> [Smooch Core] Add new endpoints</a>

**Comment by lemieux** [comment]
:+1:

**Comment by mspensieri** [comment]
👍

**Comment by dannytranlx** [comment]
👍

**Pull request merged**
